-- MySQL Script generated by MySQL Workbench
-- Wed Dec 25 20:25:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gopark
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gopark
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gopark` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gopark` ;

-- -----------------------------------------------------
-- Table `gopark`.`DRIVER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`DRIVER` (
  `id` BIGINT NOT NULL auto_increment,
  `driver_username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `car_plate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopark`.`MANAGER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`MANAGER` (
  `id` BIGINT NOT NULL auto_increment,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopark`.`PARKING_LOT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`PARKING_LOT` (
  `id` BIGINT NOT NULL auto_increment,
  `longitude` decimal(10,8) NOT NULL,
  `latitude` decimal(10,8) NOT NULL,
  `base_price` FLOAT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `manager_id` BIGINT NULL,
  `total_spots` INT NOT NULL,
  `occupied_spots` INT NOT NULL,
  `current_price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Lot_Manager_idx` (`manager_id` ASC) INVISIBLE,
  CONSTRAINT `Lot_Manager`
    FOREIGN KEY (`manager_id`)
    REFERENCES `gopark`.`MANAGER` (`id`)
    ON DELETE set null
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopark`.`PARKING_SPOT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`PARKING_SPOT` (
  `parking_lot_id` BIGINT NOT NULL,
  `number` INT NOT NULL,
  `type` ENUM('regular', 'disabled', 'EV charging') NOT NULL default 'regular', -- "regular" , "disabled", "EV charging"
  `state` ENUM('available', 'occupied', 'reserved') NOT NULL default 'available', -- "available", "occupied", "reserved"
  PRIMARY KEY (`parking_lot_id`,  `number`),
  CONSTRAINT `LOT_ID`
    FOREIGN KEY (`parking_lot_id`)
    REFERENCES `gopark`.`PARKING_LOT` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopark`.`RESERVATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`RESERVATION` (
  `id` BIGINT NOT NULL auto_increment,
  `driver_id` BIGINT NULL,
  `lot_id` BIGINT NOT NULL,
  `spot_number` INT NOT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `arrival` DATETIME NULL,
  `departure` DATETIME NULL,
  `cost` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `driver_recerv_idx` (`driver_id` ASC) VISIBLE,
  INDEX `lot_recerv_idx` (`lot_id` ASC) VISIBLE,
  CONSTRAINT `driver_recerv`
    FOREIGN KEY (`driver_id`)
    REFERENCES `gopark`.`DRIVER` (`id`)
    ON DELETE set null
    ON UPDATE NO ACTION,
  CONSTRAINT `lot_recerv`
    FOREIGN KEY (`lot_id`)
    REFERENCES `gopark`.`PARKING_LOT` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopark`.`VIOLATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`VIOLATION` (
  `id` BIGINT NOT NULL auto_increment,
  `type` ENUM('overstay', 'non-use') NOT NULL, -- "overstay", "non-use" 
  `penalty` FLOAT NOT NULL,
  `paid` bool NOT NULL,
  `reservation_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `reserv_violation_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `reserv_violation`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `gopark`.`RESERVATION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopark`.`ADMINISTRATOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`ADMINISTRATOR` (
  `id` BIGINT NOT NULL auto_increment,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gopark`.`DRIVER_NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`DRIVER_NOTIFICATION` (
  `id` BIGINT NOT NULL auto_increment,
  `driver_id` BIGINT NOT NULL,
   INDEX `driver_notifi_idx` (`driver_id` ASC) VISIBLE,
  CONSTRAINT `driver_notifi`
    FOREIGN KEY (`driver_id`)
    REFERENCES `gopark`.`DRIVER` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION,
  `content` text NOT NULL,
  `time` datetime NOT NULL,
   PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `gopark`.`MANAGER_NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gopark`.`MANAGER_NOTIFICATION` (
  `id` BIGINT NOT NULL auto_increment,
  `manager_id` BIGINT NOT NULL,
   INDEX `Manager_notifi_idx` (`manager_id` ASC) VISIBLE,
   CONSTRAINT `Manager_notifi`
    FOREIGN KEY (`manager_id`)
    REFERENCES `gopark`.`MANAGER` (`id`)
    ON DELETE cascade
    ON UPDATE no action,
  `content` text NOT NULL,
  `time` datetime NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX idx_reservation_time ON RESERVATION(lot_id, start_time, end_time);
CREATE INDEX reservation_departure_time ON RESERVATION(end_time, arrival, departure);
CREATE INDEX reservation_arrival_time ON RESERVATION (end_time, arrival, start_time);
CREATE INDEX idx_occupied_spots ON `gopark`.`PARKING_LOT`(`occupied_spots`);
CREATE INDEX idx_manager_occupied_spots ON `gopark`.`PARKING_LOT`(manager_id, id, occupied_spots, total_spots);
CREATE INDEX reservation_cost ON RESERVATION (lot_id, cost);

ALTER TABLE `gopark`.`DRIVER` ADD UNIQUE (`driver_username`);
ALTER TABLE `gopark`.`MANAGER` ADD UNIQUE (`username`);
ALTER TABLE `gopark`.`PARKING_LOT`
ADD UNIQUE INDEX unique_location (`longitude`, `latitude`);
ALTER TABLE `gopark`.`ADMINISTRATOR` ADD UNIQUE (`username`);



ALTER TABLE `gopark`.`VIOLATION`
ADD CONSTRAINT chk_positive_penalty 
CHECK (`penalty` > 0);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
